/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frontend;

import backend.Serializacao;
import backend.Sistema;

/**
 *
 * @author Marco
 */
public class JanAdministradores extends javax.swing.JFrame {

    private Sistema sistema;
    private Serializacao dados;

    public JanAdministradores(Sistema sistema, Serializacao dados) {
        initComponents();
        this.sistema = sistema;
        this.dados = dados;
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BtnCentro = new javax.swing.JButton();
        BtnGestores = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        Sair = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 97, 172));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Administrador");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 12, 250, 60));

        BtnCentro.setBackground(new java.awt.Color(255, 255, 255));
        BtnCentro.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        BtnCentro.setForeground(new java.awt.Color(0, 0, 0));
        BtnCentro.setText("Centro De Vacinação");
        BtnCentro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCentroActionPerformed(evt);
            }
        });
        getContentPane().add(BtnCentro, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 119, 150, -1));

        BtnGestores.setBackground(new java.awt.Color(255, 255, 255));
        BtnGestores.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        BtnGestores.setForeground(new java.awt.Color(0, 0, 0));
        BtnGestores.setText("Gestores");
        BtnGestores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGestoresActionPerformed(evt);
            }
        });
        getContentPane().add(BtnGestores, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 205, 150, -1));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Estatística");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 162, 150, -1));

        Sair.setText("Sair");
        Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairActionPerformed(evt);
            }
        });
        getContentPane().add(Sair, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 582, 73, -1));

        jLabel2.setBackground(new java.awt.Color(0, 38, 61));
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-5, -7, 520, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCentroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCentroActionPerformed
        dispose();
        JanAdminListCentro janela = new JanAdminListCentro(sistema, dados);
        janela.setVisible(true);
    }//GEN-LAST:event_BtnCentroActionPerformed

    private void BtnGestoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGestoresActionPerformed
        dispose();
        JanAdminListGestores janela = new JanAdminListGestores(sistema, dados);
        janela.setVisible(true);
    }//GEN-LAST:event_BtnGestoresActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
        JanAdminEstat janela = new JanAdminEstat(sistema, dados);
        janela.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairActionPerformed
        dados.guardar(sistema);
        System.exit(0);
    }//GEN-LAST:event_SairActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCentro;
    private javax.swing.JButton BtnGestores;
    private javax.swing.JButton Sair;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
