/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frontend;

import backend.Serializacao;
import backend.Sistema;
import backend.Centro_Vacinacao;
import backend.Gestor;

/**
 *
 * @author Marco
 */
public class JanGestor extends javax.swing.JFrame {

    private Sistema sistema;
    private Serializacao dados;

    public JanGestor(Sistema sistema, Serializacao dados) {
        initComponents();
        this.sistema = sistema;
        this.dados = dados;
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        BtnCentroVacinacao = new javax.swing.JButton();
        BtnMarcacoes = new javax.swing.JButton();
        BtnStock = new javax.swing.JButton();
        BtnUtente = new javax.swing.JButton();
        BtnSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 38, 61));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Gestores");

        BtnCentroVacinacao.setBackground(new java.awt.Color(255, 255, 255));
        BtnCentroVacinacao.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        BtnCentroVacinacao.setForeground(new java.awt.Color(0, 0, 0));
        BtnCentroVacinacao.setText("Centro de vacinação");
        BtnCentroVacinacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCentroVacinacaoActionPerformed(evt);
            }
        });

        BtnMarcacoes.setBackground(new java.awt.Color(255, 255, 255));
        BtnMarcacoes.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        BtnMarcacoes.setForeground(new java.awt.Color(0, 0, 0));
        BtnMarcacoes.setText("Marcações");
        BtnMarcacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMarcacoesActionPerformed(evt);
            }
        });

        BtnStock.setBackground(new java.awt.Color(255, 255, 255));
        BtnStock.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        BtnStock.setForeground(new java.awt.Color(0, 0, 0));
        BtnStock.setText("Stock Vacinas");
        BtnStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnStockActionPerformed(evt);
            }
        });

        BtnUtente.setBackground(new java.awt.Color(255, 255, 255));
        BtnUtente.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        BtnUtente.setForeground(new java.awt.Color(0, 0, 0));
        BtnUtente.setText("Utentes");
        BtnUtente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUtenteActionPerformed(evt);
            }
        });

        BtnSair.setBackground(new java.awt.Color(255, 255, 255));
        BtnSair.setForeground(new java.awt.Color(0, 0, 0));
        BtnSair.setText("Sair");
        BtnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 210, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(BtnMarcacoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnCentroVacinacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnStock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnUtente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(214, 214, 214))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnCentroVacinacao)
                .addGap(18, 18, 18)
                .addComponent(BtnMarcacoes)
                .addGap(18, 18, 18)
                .addComponent(BtnStock)
                .addGap(18, 18, 18)
                .addComponent(BtnUtente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 180, Short.MAX_VALUE)
                .addComponent(BtnSair)
                .addGap(52, 52, 52))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCentroVacinacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCentroVacinacaoActionPerformed
        dispose();
        JanGestorCentro janela = new JanGestorCentro(sistema, dados);
        janela.setVisible(true);
    }//GEN-LAST:event_BtnCentroVacinacaoActionPerformed

    private void BtnMarcacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMarcacoesActionPerformed
        dispose();
        JanGestorMarcacoes janela = new JanGestorMarcacoes(sistema, dados);
        janela.setVisible(true);
    }//GEN-LAST:event_BtnMarcacoesActionPerformed

    private void BtnStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnStockActionPerformed
         dispose();
        JanGestorStock janela = new JanGestorStock(sistema, dados);
        janela.setVisible(true);     
    }//GEN-LAST:event_BtnStockActionPerformed

    private void BtnUtenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUtenteActionPerformed
        dispose();
        JanGestorUtentes janela = new JanGestorUtentes(sistema, dados);
        janela.setVisible(true);
    }//GEN-LAST:event_BtnUtenteActionPerformed

    private void BtnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSairActionPerformed
        dados.guardar(sistema);
        System.exit(0);
    }//GEN-LAST:event_BtnSairActionPerformed

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCentroVacinacao;
    private javax.swing.JButton BtnMarcacoes;
    private javax.swing.JButton BtnSair;
    private javax.swing.JButton BtnStock;
    private javax.swing.JButton BtnUtente;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
