/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frontend;

import backend.Serializacao;
import backend.Sistema;
import backend.Utente;
/**
 *
 * @author Marco
 */
public class JanUtente extends javax.swing.JFrame {

    private Sistema sistema;
    private Serializacao dados;

    public JanUtente(Sistema sistema, Serializacao dados) {
        initComponents();
        this.sistema = sistema;
        this.dados = dados;
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BtnDoencas = new javax.swing.JButton();
        BtnMarcacoes = new javax.swing.JButton();
        BtnDadosUtente = new javax.swing.JButton();
        BtnSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 38, 61));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Utente");

        BtnDoencas.setBackground(new java.awt.Color(255, 255, 255));
        BtnDoencas.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        BtnDoencas.setForeground(new java.awt.Color(0, 0, 0));
        BtnDoencas.setText("Doenças");
        BtnDoencas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDoencasActionPerformed(evt);
            }
        });

        BtnMarcacoes.setBackground(new java.awt.Color(255, 255, 255));
        BtnMarcacoes.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        BtnMarcacoes.setForeground(new java.awt.Color(0, 0, 0));
        BtnMarcacoes.setText("Marcação");
        BtnMarcacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMarcacoesActionPerformed(evt);
            }
        });

        BtnDadosUtente.setBackground(new java.awt.Color(255, 255, 255));
        BtnDadosUtente.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        BtnDadosUtente.setForeground(new java.awt.Color(0, 0, 0));
        BtnDadosUtente.setText("Dados Utente");
        BtnDadosUtente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDadosUtenteActionPerformed(evt);
            }
        });

        BtnSair.setBackground(new java.awt.Color(255, 255, 255));
        BtnSair.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        BtnSair.setForeground(new java.awt.Color(0, 0, 0));
        BtnSair.setText("Sair");
        BtnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(125, 125, 125)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(223, 223, 223)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(BtnMarcacoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BtnDoencas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(BtnDadosUtente, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))))
                        .addGap(0, 114, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BtnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(BtnDoencas)
                .addGap(18, 18, 18)
                .addComponent(BtnMarcacoes)
                .addGap(18, 18, 18)
                .addComponent(BtnDadosUtente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 162, Short.MAX_VALUE)
                .addComponent(BtnSair)
                .addGap(60, 60, 60))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnDoencasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDoencasActionPerformed
        dispose();
        JanUtenteDoencas janela = new JanUtenteDoencas(sistema, dados);
        janela.setVisible(true);
    }//GEN-LAST:event_BtnDoencasActionPerformed

    private void BtnMarcacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMarcacoesActionPerformed
        Utente utente = (Utente) sistema.getUtilizadorLigado();
        if(utente.isVacina_administrada()){
            dispose();
            JanUtenteVerDados janela = new JanUtenteVerDados(sistema, dados); 
            janela.setVisible(true);
        }else{
            if(utente.getCentro_vacinacao().getMarcacoesV().TemMarcacao(utente)){
                dispose();
                JanelaUtenteVerMarcaçao janela = new JanelaUtenteVerMarcaçao(sistema, dados); 
                janela.setVisible(true);
            } else{
                dispose();
                JanelaUtenteVerMarcaçao janela = new JanelaUtenteVerMarcaçao(sistema, dados);
                janela.setVisible(true);
            }
        }
    
    }//GEN-LAST:event_BtnMarcacoesActionPerformed

    private void BtnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSairActionPerformed
         dados.guardar(sistema);
        System.exit(0);
    }//GEN-LAST:event_BtnSairActionPerformed

    private void BtnDadosUtenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDadosUtenteActionPerformed
       dispose();
    }//GEN-LAST:event_BtnDadosUtenteActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnDadosUtente;
    private javax.swing.JButton BtnDoencas;
    private javax.swing.JButton BtnMarcacoes;
    private javax.swing.JButton BtnSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
